- name: Download VSCode Server install script
  ansible.builtin.get_url:
    url: https://aka.ms/install-vscode-server/setup.sh
    dest: ./vscode-setup.sh
    mode: 0755

- name: Run install script
  ansible.builtin.command:
    cmd: ./vscode-setup.sh
  changed_when: true

# - name: Add alias from vscode-server to code
#   ansible.builtin.lineinfile:
#     path: ~/.bashrc
#     line: "alias code='code-server serve-local'"
#     regexp: ^alias code='code-server serve-local'$
#     state: present
