# https://github.com/particledecay/ansible-jsonpatch
# https://github.com/gantsign/ansible-role-visual-studio-code-extensions/blob/master/library/visual_studio_code_extensions.py
# https://github.com/gantsign/ansible-role-visual-studio-code
---
- name: Configure Ansible-Python Virtual Environment
  hosts: linux_dev
  vars:
    vscode_venv_default_path: ~/.venv/ansible-dev
  tasks:
    - name: Install Python 3.9+
      ansible.builtin.package:
        name: python39
      # when:

    - name: Create venv
      ansible.builtin.command:
        cmd: python3 -m venv {{ vscode_venv_default_path }}
      changed_when: true

    - name: Install Python Packages
      ansible.builtin.pip:
        name: "{{ item }}"
        virtualenv: "{{ vscode_venv_default_path }}"
      with_items:
        - ansible==7.1.0
        - ansible-core>2.14.0,<2.15.0
        - ansible-lint

- name: Configure VSCode
  hosts: localhost
  vars:
    vscode_venv_default_path: ~/.venv/ansible-dev
    vscode_default_python_interpreter: python3
    vscode_default_podman_path: podman
    # vscode_default_podman_path: /app/tools/podman/bin/podman-remote
  tasks:
    - name: Read current settings.json
      ansible.builtin.slurp:
        src: ~/.vscode-server/data/Machine/settings.json
      register: current_settings_json

    # - name: Setup Remote Docker Config
    #   hyperkineticnerd.vscode.json_patch:
    #     src: ~/.vscode-server/data/Machine/settings.json
    #     pretty: true
    #     operations:
    #       - op: add
    #         path: "/docker.dockerPath"
    #         value: "podman"
    #       - op: add
    #         path: "/docker.environment/DOCKER_HOST"
    #         value: "unix:///run/user/$(id -u)/podman/podman.sock"

    - name: Setup Python Config
      hyperkineticnerd.vscode.json_patch:
        src: ~/.vscode-server/data/Machine/settings.json
        pretty: true
        operations:
          - op: add
            path: "/python.venvPath"
            value: "~/.venv"

    - name: Setup Ansible Config
      hyperkineticnerd.vscode.json_patch:
        src: ~/.vscode-server/data/Machine/settings.json
        pretty: true
        operations:
          - op: add
            path: "/ansible.python.activationScript"
            value: "{{ vscode_venv_default_path }}/bin/activate"
          - op: add
            path: "/ansible.python.interpreterPath"
            value: "{{ vscode_default_python_interpreter }}"
