---
# tasks file for vscode_install
- include_tasks: "{{ ansible_facts['os_family'] }}/install.yml"
  when: vscode_install_method == 'dnf'

- include_tasks: FlatPak/install.yml
  when: vscode_install_method == 'FlatPak'
